CREATE TABLE `ANIME_USER` (
  `ID` int(20) NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `MOBILE` varchar(100) DEFAULT NULL COMMENT '手机',
  `PORTRAIT_URL` varchar(300) DEFAULT NULL COMMENT '头像地址',
  `LOGINNAME` varchar(100) DEFAULT NULL COMMENT '登录名称',
  `NICKNAME` varchar(100) DEFAULT NULL COMMENT '昵称',
  `PASSWD` varchar(100) DEFAULT NULL COMMENT '密码',
  `SALT` varchar(40) DEFAULT NULL COMMENT 'shiro加密盐',
  `GENDER` smallint(6) DEFAULT NULL COMMENT '性别:-1保密,0女，1男',
  `STATUS` smallint(6) DEFAULT NULL COMMENT '状态:1开通,-1冻结',
  `CREATE_TIMESTAMP` bigint(20) DEFAULT NULL COMMENT '创建时间戳',
  `EMAIL` varchar(200) DEFAULT NULL COMMENT '邮箱',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
insert into `ANIME_USER` value ('1','18300197590',NULL,'admin','椎名真白',NULL,'0','1',NULL,'1101939669@qq.com')

DROP TABLE IF EXISTS `ANIME_MANAGER`;
CREATE TABLE `ANIME_MANAGER` (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `ROLE_ID` int(20) DEFAULT NULL COMMENT '角色ID',
  `CUSTOMER_ID` int(20) DEFAULT NULL COMMENT '用户ID',
  `STATUS` smallint(6) DEFAULT NULL COMMENT '状态: -1冻结, 1正常',
  `CREATE_TIMESTAMP` bigint(20) DEFAULT NULL COMMENT '创建时间戳',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE anime_manager ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES anime_user(ID) on delete cascade on update cascade;

DROP TABLE IF EXISTS `ANIME_ROLE`;
CREATE TABLE `ANIME_ROLE` (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(30) DEFAULT NULL COMMENT '角色名称',
  `DESCRIPTION` varchar(100) DEFAULT NULL COMMENT '角色描述',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `TB_ROLE_PERM`;
CREATE TABLE `TB_ROLE_PERM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `ROLE_ID` int(11) DEFAULT NULL COMMENT '角色id',
  `PERMISSION_ID` int(11) DEFAULT NULL COMMENT '权限id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ANIME_PERMISSION`;
CREATE TABLE `ANIME_PERMISSION` (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL COMMENT '权限名称(用户管理-查询)',
  `URL` varchar(255) DEFAULT NULL COMMENT 'url地址',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ANIME_SHIRO_FILTER`;
CREATE TABLE `ANIME_SHIRO_FILTER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL COMMENT '资源字段名',
  `PERMS` varchar(255) DEFAULT NULL COMMENT '所需权限',
  `SORT_ORDER` int(11) DEFAULT NULL COMMENT '排序等级',
  `CREATE_TIMESTAMP` bigint(20) DEFAULT NULL COMMENT '创建时间戳',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;